# Configuration settings for odp_loader
AssessedValues:
  socrata_url: "https://datacatalog.cookcountyil.gov/resource/"
  socrata_key: "cookcounty"
  id: "uzyt-m557"
  batch_column: "year"
  uid: "row_id"
  dtype:
    pin: object
    year: Int64
    class: object
    township_code: object
    township_name: object
    mailed_bldg: Float64
    mailed_land: Float64
    mailed_tot: Float64
    certified_bldg: Float64
    certified_land: Float64
    certified_tot: Float64
    board_bldg: Float64
    nbhd: object
    board_land: Float64
    board_tot: Float64
    row_id: object
  destination:
    schema: odp
    table: CCAO_AssessedValues

ExemptProperties: 
  socrata_url: "https://datacatalog.cookcountyil.gov/resource/"
  socrata_key: "cookcounty"
  id: "vgzx-68gb"
  batch_column: "year" 
  uid: "row_id"
  dtype:
    pin: object
    year: object
    township_name: object
    township_code: object
    owner_num: object
    owner_name: object
    class: object
    property_address: object
    property_city: object
    lon: float64
    lat: float64
    row_id: object
    format:
      year: "\\d{4}"
  destination:
    schema: odp
    table: CCAO_ExemptProperties
  ddl:
    row_id: NVARCHAR(18)
    pin: NVARCHAR(14)
    year: NVARCHAR(4)
    township_name: NVARCHAR(50)
    township_code: NVARCHAR(10)
    owner_num: NVARCHAR(20)
    owner_name: NVARCHAR(255)
    class: NVARCHAR(10)
    property_address: NVARCHAR(255)
    property_city: NVARCHAR(100)
    lon: FLOAT
    lat: FLOAT

CommercialCharacteristics:
    id: csik-bsws    
    batch_column: year
    socrata_url: "https://datacatalog.cookcountyil.gov/resource/"
    dtype:
      keypin: object
      pins: object
      year: float64
      township: object
      sheet: object
      class_es: object
      studiounits: float64
      _1brunits: float64
      _2brunits: float64
      _3brunits: float64
      _4brunits: float64
      tot_units: float64
      address: object
      adj_rent_sf: float64
      aprx_comm_sf: float64
      apt: float64
      avgdailyrate: float64
      bldgsf: float64
      caprate: float64
      carwash: object
      category: float64
      ceilingheight: object
      cost_day_bed: float64
      costapproach_sf: float64
      covidadjvacancy: float64
      ebitda: float64
      egi: float64
      excesslandarea: float64
      excesslandval: float64
      exp: float64
      f_r: object
      finalmarketvalue: float64
      finalmarketvalue_bed: float64
      finalmarketvalue_key: float64
      finalmarketvalue_sf: float64
      finalmarketvalue_unit: float64
      idphlicense: float64
      incomemarketvalue: float64
      incomemarketvalue_sf: float64
      investmentrating: object
      land_bldg: float64
      landsf: float64
      model: object
      nbhd: float64
      netrentablesf: float64
      noi: float64
      oiltankvalue_atypicaloby: float64
      owner: float64
      parking: float64
      parkingsf: float64
      pctownerinterest: float64
      permit_partial_demovalue: object
      pgi: float64
      property_name_description: object
      property_type_use: object
      reportedoccupancy: float64
      revenuebed_day: float64
      revpar: float64
      roomrev: float64
      salecompmarketvalue_sf: float64
      sap: float64
      sapdeduction: float64
      saptier: float64
      stories: float64
      subclass2: object
      taxdist: object
      taxpayer: float64
      totalrevreported: float64
      totalexp: float64
      totallandval: float64
      totalrev: float64
      townregion: object
      vacancy: float64
      yearbuilt: float64
    destination:
      schema: odp
      table: CCAO_CommercialCharacteristics
    ddl:
      keypin: VARCHAR(25)
      pins: VARCHAR(MAX)
      year: FLOAT
      township: VARCHAR(500)
      sheet: VARCHAR(500)
      class_es: VARCHAR(MAX)
      studiounits: FLOAT
      _1brunits: FLOAT
      _2brunits: FLOAT
      _3brunits: FLOAT
      _4brunits: FLOAT
      tot_units: FLOAT
      address: VARCHAR(500)
      adj_rent_sf: FLOAT
      aprx_comm_sf: FLOAT
      apt: FLOAT
      avgdailyrate: FLOAT
      bldgsf: FLOAT
      caprate: FLOAT
      carwash: VARCHAR(500)
      category: FLOAT
      ceilingheight: VARCHAR(500)
      cost_day_bed: FLOAT
      costapproach_sf: FLOAT
      covidadjvacancy: FLOAT
      ebitda: FLOAT
      egi: FLOAT
      excesslandarea: FLOAT
      excesslandval: FLOAT
      exp: FLOAT
      f_r: VARCHAR(500)
      finalmarketvalue: FLOAT
      finalmarketvalue_bed: FLOAT
      finalmarketvalue_key: FLOAT
      finalmarketvalue_sf: FLOAT
      finalmarketvalue_unit: FLOAT
      idphlicense: FLOAT
      incomemarketvalue: FLOAT
      incomemarketvalue_sf: FLOAT
      investmentrating: VARCHAR(500)
      land_bldg: FLOAT
      landsf: FLOAT
      model: VARCHAR(500)
      nbhd: FLOAT
      netrentablesf: FLOAT
      noi: FLOAT
      oiltankvalue_atypicaloby: FLOAT
      owner: FLOAT
      parking: FLOAT
      parkingsf: FLOAT
      pctownerinterest: FLOAT
      permit_partial_demovalue: VARCHAR(500)
      pgi: FLOAT
      property_name_description: VARCHAR(500)
      property_type_use: VARCHAR(500)
      reportedoccupancy: FLOAT
      revenuebed_day: FLOAT
      revpar: FLOAT
      roomrev: FLOAT
      salecompmarketvalue_sf: FLOAT
      sap: FLOAT
      sapdeduction: FLOAT
      saptier: FLOAT
      stories: FLOAT
      subclass2: VARCHAR(500)
      taxdist: VARCHAR(500)
      taxpayer: FLOAT
      totalrevreported: FLOAT
      totalexp: FLOAT
      totallandval: FLOAT
      totalrev: FLOAT
      townregion: VARCHAR(500)
      vacancy: FLOAT
      yearbuilt: FLOAT
